### ISSUE TITLE
Don't run formatter if file present in root

### ISSUE THREAD

**Issue by rawhat** [nvimdev/guard.nvim#76]
The `find` property is great for noting when to run a task. I see that there is also `ignore_pattern` for a particular file.  But say I have two formatters, one of which I run conditionally if a file is present, and the other only if that first one is not matched, how can I do this with the current API?  The original issue asking for the conditional with a function would cover both cases, where this is only an "if exists".  Let me know if I'm missing something!

**Comment by barrett-ruth** [comment]
@glepnir something to maybe consider. People want things to run in weird use cases. Turning a variable into a with a few lines is reasonable I think

**Comment by glepnir** [comment]
maybe we can allow communication between multiple configurations.

**Comment by xiaoshihou514** [comment]
or maybe provide api for writing unique formatting logics in the `fn` field

**Comment by pauldiloreto** [comment]
I understand your ask for a function that lets you express both cases. I agree this could lead to cleaner configurations for complex use cases such as yours.

Regarding your ask for how to cover your use case with the current API, wouldn't you be able to successfully achieve this via:
```lua
local matched_file = 'some-file';

ft('lang'):fmt({
  -- First formatter
  ...
  find = { matched_file },
}):append({
  -- Second formatter
  ...
  ignore_pattern = { matched_file },
})
```

The second formatter isn't explicitly triggering _because_ the first one didn't match, however, this is functionally the same because the `find`/`ignore_pattern` parameters are set to the opposite of each other. So functionally, the second formatter only runs when the first one doesn't run & vice versa.

Wouldn't this work? Or perhaps I'm missing something?

**Comment by pauldiloreto** [comment]
> @pauldiloreto `ignore_pattern` matches against the file you are formatting and not a root dir file
Got it, my mistake.

With that note, would it be sufficient to support glob patterns so we could pass a negative wildcard? Or perhaps just regex at that point?
Or would it be better to just have a function API like you mentioned earlier in this thread?

**Comment by xiaoshihou514** [comment]
I plan to do the api approach since it offers more flexibility (if no one is opposed to that)

**Comment by pauldiloreto** [comment]
> I plan to do the api approach since it offers more flexibility (if no one is opposed to that)

Sounds good to me.
I just realized that this would also allow support for the use case of scanning a file (i.e. `package.json`) for certain keys and only running a formatter if some configuration is present there.

**Comment by barrett-ruth** [comment]
> I plan to do the api approach since it offers more flexibility (if no one is opposed to that)

sounds good to me
